template = "config/embedding.gotmpl"

[elasticsearch]
# endpoint = ["http://localhost:9201", "http://localhost:9200"]
endpoint = ["https://localhost:8080","https://localhost:8081","https://localhost:8082","https://localhost:8083","https://localhost:8084"]
index = "alma-full"
apikey = "%%ELASTIC_API_KEY%%"
debug = true